// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: growth/weather/weather.proto

package weather

import (
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

//======================== 获取某个城市的天气生活指数 ========================
type GetWeatherLifeByCityReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	City string `protobuf:"bytes,1,opt,name=city,proto3" json:"city,omitempty"`
}

func (x *GetWeatherLifeByCityReq) Reset() {
	*x = GetWeatherLifeByCityReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_growth_weather_weather_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetWeatherLifeByCityReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWeatherLifeByCityReq) ProtoMessage() {}

func (x *GetWeatherLifeByCityReq) ProtoReflect() protoreflect.Message {
	mi := &file_growth_weather_weather_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWeatherLifeByCityReq.ProtoReflect.Descriptor instead.
func (*GetWeatherLifeByCityReq) Descriptor() ([]byte, []int) {
	return file_growth_weather_weather_proto_rawDescGZIP(), []int{0}
}

func (x *GetWeatherLifeByCityReq) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

type GetWeatherLifeByCityRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32                             `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string                            `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data *GetWeatherLifeByCityRes_LifeInfo `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *GetWeatherLifeByCityRes) Reset() {
	*x = GetWeatherLifeByCityRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_growth_weather_weather_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetWeatherLifeByCityRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWeatherLifeByCityRes) ProtoMessage() {}

func (x *GetWeatherLifeByCityRes) ProtoReflect() protoreflect.Message {
	mi := &file_growth_weather_weather_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWeatherLifeByCityRes.ProtoReflect.Descriptor instead.
func (*GetWeatherLifeByCityRes) Descriptor() ([]byte, []int) {
	return file_growth_weather_weather_proto_rawDescGZIP(), []int{1}
}

func (x *GetWeatherLifeByCityRes) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetWeatherLifeByCityRes) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GetWeatherLifeByCityRes) GetData() *GetWeatherLifeByCityRes_LifeInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

//======================== 获取某个城市的天气 ========================
type GetWeatherByCityReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	City string `protobuf:"bytes,1,opt,name=city,proto3" json:"city,omitempty"`
}

func (x *GetWeatherByCityReq) Reset() {
	*x = GetWeatherByCityReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_growth_weather_weather_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetWeatherByCityReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWeatherByCityReq) ProtoMessage() {}

func (x *GetWeatherByCityReq) ProtoReflect() protoreflect.Message {
	mi := &file_growth_weather_weather_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWeatherByCityReq.ProtoReflect.Descriptor instead.
func (*GetWeatherByCityReq) Descriptor() ([]byte, []int) {
	return file_growth_weather_weather_proto_rawDescGZIP(), []int{2}
}

func (x *GetWeatherByCityReq) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

type GetWeatherByCityRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32        `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string       `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data *WeatherInfo `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *GetWeatherByCityRes) Reset() {
	*x = GetWeatherByCityRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_growth_weather_weather_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetWeatherByCityRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWeatherByCityRes) ProtoMessage() {}

func (x *GetWeatherByCityRes) ProtoReflect() protoreflect.Message {
	mi := &file_growth_weather_weather_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWeatherByCityRes.ProtoReflect.Descriptor instead.
func (*GetWeatherByCityRes) Descriptor() ([]byte, []int) {
	return file_growth_weather_weather_proto_rawDescGZIP(), []int{3}
}

func (x *GetWeatherByCityRes) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetWeatherByCityRes) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GetWeatherByCityRes) GetData() *WeatherInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

type WeatherInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Realtime *WeatherInfo_Realtime `protobuf:"bytes,1,opt,name=realtime,proto3" json:"realtime,omitempty"`
	Future   []*WeatherInfo_Future `protobuf:"bytes,2,rep,name=future,proto3" json:"future,omitempty"`
}

func (x *WeatherInfo) Reset() {
	*x = WeatherInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_growth_weather_weather_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WeatherInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeatherInfo) ProtoMessage() {}

func (x *WeatherInfo) ProtoReflect() protoreflect.Message {
	mi := &file_growth_weather_weather_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeatherInfo.ProtoReflect.Descriptor instead.
func (*WeatherInfo) Descriptor() ([]byte, []int) {
	return file_growth_weather_weather_proto_rawDescGZIP(), []int{4}
}

func (x *WeatherInfo) GetRealtime() *WeatherInfo_Realtime {
	if x != nil {
		return x.Realtime
	}
	return nil
}

func (x *WeatherInfo) GetFuture() []*WeatherInfo_Future {
	if x != nil {
		return x.Future
	}
	return nil
}

type GetWeatherLifeByCityRes_LifeInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kongtiao  *GetWeatherLifeByCityRes_LifeInfo_Kongtiao  `protobuf:"bytes,1,opt,name=kongtiao,proto3" json:"kongtiao,omitempty"`
	Guomin    *GetWeatherLifeByCityRes_LifeInfo_Guomin    `protobuf:"bytes,2,opt,name=guomin,proto3" json:"guomin,omitempty"`
	Shushidu  *GetWeatherLifeByCityRes_LifeInfo_Shushidu  `protobuf:"bytes,3,opt,name=shushidu,proto3" json:"shushidu,omitempty"`
	Chuanyi   *GetWeatherLifeByCityRes_LifeInfo_Chuanyi   `protobuf:"bytes,4,opt,name=chuanyi,proto3" json:"chuanyi,omitempty"`
	Diaoyu    *GetWeatherLifeByCityRes_LifeInfo_Diaoyu    `protobuf:"bytes,5,opt,name=diaoyu,proto3" json:"diaoyu,omitempty"`
	Ganmao    *GetWeatherLifeByCityRes_LifeInfo_Ganmao    `protobuf:"bytes,6,opt,name=ganmao,proto3" json:"ganmao,omitempty"`
	Ziwaixian *GetWeatherLifeByCityRes_LifeInfo_Ziwaixian `protobuf:"bytes,7,opt,name=ziwaixian,proto3" json:"ziwaixian,omitempty"`
	Xiche     *GetWeatherLifeByCityRes_LifeInfo_Xiche     `protobuf:"bytes,8,opt,name=xiche,proto3" json:"xiche,omitempty"`
	Yundong   *GetWeatherLifeByCityRes_LifeInfo_Yundong   `protobuf:"bytes,9,opt,name=yundong,proto3" json:"yundong,omitempty"`
	Daisan    *GetWeatherLifeByCityRes_LifeInfo_Daisan    `protobuf:"bytes,10,opt,name=daisan,proto3" json:"daisan,omitempty"`
}

func (x *GetWeatherLifeByCityRes_LifeInfo) Reset() {
	*x = GetWeatherLifeByCityRes_LifeInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_growth_weather_weather_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetWeatherLifeByCityRes_LifeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWeatherLifeByCityRes_LifeInfo) ProtoMessage() {}

func (x *GetWeatherLifeByCityRes_LifeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_growth_weather_weather_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWeatherLifeByCityRes_LifeInfo.ProtoReflect.Descriptor instead.
func (*GetWeatherLifeByCityRes_LifeInfo) Descriptor() ([]byte, []int) {
	return file_growth_weather_weather_proto_rawDescGZIP(), []int{1, 0}
}

func (x *GetWeatherLifeByCityRes_LifeInfo) GetKongtiao() *GetWeatherLifeByCityRes_LifeInfo_Kongtiao {
	if x != nil {
		return x.Kongtiao
	}
	return nil
}

func (x *GetWeatherLifeByCityRes_LifeInfo) GetGuomin() *GetWeatherLifeByCityRes_LifeInfo_Guomin {
	if x != nil {
		return x.Guomin
	}
	return nil
}

func (x *GetWeatherLifeByCityRes_LifeInfo) GetShushidu() *GetWeatherLifeByCityRes_LifeInfo_Shushidu {
	if x != nil {
		return x.Shushidu
	}
	return nil
}

func (x *GetWeatherLifeByCityRes_LifeInfo) GetChuanyi() *GetWeatherLifeByCityRes_LifeInfo_Chuanyi {
	if x != nil {
		return x.Chuanyi
	}
	return nil
}

func (x *GetWeatherLifeByCityRes_LifeInfo) GetDiaoyu() *GetWeatherLifeByCityRes_LifeInfo_Diaoyu {
	if x != nil {
		return x.Diaoyu
	}
	return nil
}

func (x *GetWeatherLifeByCityRes_LifeInfo) GetGanmao() *GetWeatherLifeByCityRes_LifeInfo_Ganmao {
	if x != nil {
		return x.Ganmao
	}
	return nil
}

func (x *GetWeatherLifeByCityRes_LifeInfo) GetZiwaixian() *GetWeatherLifeByCityRes_LifeInfo_Ziwaixian {
	if x != nil {
		return x.Ziwaixian
	}
	return nil
}

func (x *GetWeatherLifeByCityRes_LifeInfo) GetXiche() *GetWeatherLifeByCityRes_LifeInfo_Xiche {
	if x != nil {
		return x.Xiche
	}
	return nil
}

func (x *GetWeatherLifeByCityRes_LifeInfo) GetYundong() *GetWeatherLifeByCityRes_LifeInfo_Yundong {
	if x != nil {
		return x.Yundong
	}
	return nil
}

func (x *GetWeatherLifeByCityRes_LifeInfo) GetDaisan() *GetWeatherLifeByCityRes_LifeInfo_Daisan {
	if x != nil {
		return x.Daisan
	}
	return nil
}

type GetWeatherLifeByCityRes_LifeInfo_Kongtiao struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	V   string `protobuf:"bytes,1,opt,name=v,proto3" json:"v,omitempty"`
	Des string `protobuf:"bytes,2,opt,name=des,proto3" json:"des,omitempty"`
}

func (x *GetWeatherLifeByCityRes_LifeInfo_Kongtiao) Reset() {
	*x = GetWeatherLifeByCityRes_LifeInfo_Kongtiao{}
	if protoimpl.UnsafeEnabled {
		mi := &file_growth_weather_weather_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetWeatherLifeByCityRes_LifeInfo_Kongtiao) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWeatherLifeByCityRes_LifeInfo_Kongtiao) ProtoMessage() {}

func (x *GetWeatherLifeByCityRes_LifeInfo_Kongtiao) ProtoReflect() protoreflect.Message {
	mi := &file_growth_weather_weather_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWeatherLifeByCityRes_LifeInfo_Kongtiao.ProtoReflect.Descriptor instead.
func (*GetWeatherLifeByCityRes_LifeInfo_Kongtiao) Descriptor() ([]byte, []int) {
	return file_growth_weather_weather_proto_rawDescGZIP(), []int{1, 0, 0}
}

func (x *GetWeatherLifeByCityRes_LifeInfo_Kongtiao) GetV() string {
	if x != nil {
		return x.V
	}
	return ""
}

func (x *GetWeatherLifeByCityRes_LifeInfo_Kongtiao) GetDes() string {
	if x != nil {
		return x.Des
	}
	return ""
}

type GetWeatherLifeByCityRes_LifeInfo_Guomin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	V   string `protobuf:"bytes,1,opt,name=v,proto3" json:"v,omitempty"`
	Des string `protobuf:"bytes,2,opt,name=des,proto3" json:"des,omitempty"`
}

func (x *GetWeatherLifeByCityRes_LifeInfo_Guomin) Reset() {
	*x = GetWeatherLifeByCityRes_LifeInfo_Guomin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_growth_weather_weather_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetWeatherLifeByCityRes_LifeInfo_Guomin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWeatherLifeByCityRes_LifeInfo_Guomin) ProtoMessage() {}

func (x *GetWeatherLifeByCityRes_LifeInfo_Guomin) ProtoReflect() protoreflect.Message {
	mi := &file_growth_weather_weather_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWeatherLifeByCityRes_LifeInfo_Guomin.ProtoReflect.Descriptor instead.
func (*GetWeatherLifeByCityRes_LifeInfo_Guomin) Descriptor() ([]byte, []int) {
	return file_growth_weather_weather_proto_rawDescGZIP(), []int{1, 0, 1}
}

func (x *GetWeatherLifeByCityRes_LifeInfo_Guomin) GetV() string {
	if x != nil {
		return x.V
	}
	return ""
}

func (x *GetWeatherLifeByCityRes_LifeInfo_Guomin) GetDes() string {
	if x != nil {
		return x.Des
	}
	return ""
}

type GetWeatherLifeByCityRes_LifeInfo_Shushidu struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	V   string `protobuf:"bytes,1,opt,name=v,proto3" json:"v,omitempty"`
	Des string `protobuf:"bytes,2,opt,name=des,proto3" json:"des,omitempty"`
}

func (x *GetWeatherLifeByCityRes_LifeInfo_Shushidu) Reset() {
	*x = GetWeatherLifeByCityRes_LifeInfo_Shushidu{}
	if protoimpl.UnsafeEnabled {
		mi := &file_growth_weather_weather_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetWeatherLifeByCityRes_LifeInfo_Shushidu) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWeatherLifeByCityRes_LifeInfo_Shushidu) ProtoMessage() {}

func (x *GetWeatherLifeByCityRes_LifeInfo_Shushidu) ProtoReflect() protoreflect.Message {
	mi := &file_growth_weather_weather_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWeatherLifeByCityRes_LifeInfo_Shushidu.ProtoReflect.Descriptor instead.
func (*GetWeatherLifeByCityRes_LifeInfo_Shushidu) Descriptor() ([]byte, []int) {
	return file_growth_weather_weather_proto_rawDescGZIP(), []int{1, 0, 2}
}

func (x *GetWeatherLifeByCityRes_LifeInfo_Shushidu) GetV() string {
	if x != nil {
		return x.V
	}
	return ""
}

func (x *GetWeatherLifeByCityRes_LifeInfo_Shushidu) GetDes() string {
	if x != nil {
		return x.Des
	}
	return ""
}

type GetWeatherLifeByCityRes_LifeInfo_Chuanyi struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	V   string `protobuf:"bytes,1,opt,name=v,proto3" json:"v,omitempty"`
	Des string `protobuf:"bytes,2,opt,name=des,proto3" json:"des,omitempty"`
}

func (x *GetWeatherLifeByCityRes_LifeInfo_Chuanyi) Reset() {
	*x = GetWeatherLifeByCityRes_LifeInfo_Chuanyi{}
	if protoimpl.UnsafeEnabled {
		mi := &file_growth_weather_weather_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetWeatherLifeByCityRes_LifeInfo_Chuanyi) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWeatherLifeByCityRes_LifeInfo_Chuanyi) ProtoMessage() {}

func (x *GetWeatherLifeByCityRes_LifeInfo_Chuanyi) ProtoReflect() protoreflect.Message {
	mi := &file_growth_weather_weather_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWeatherLifeByCityRes_LifeInfo_Chuanyi.ProtoReflect.Descriptor instead.
func (*GetWeatherLifeByCityRes_LifeInfo_Chuanyi) Descriptor() ([]byte, []int) {
	return file_growth_weather_weather_proto_rawDescGZIP(), []int{1, 0, 3}
}

func (x *GetWeatherLifeByCityRes_LifeInfo_Chuanyi) GetV() string {
	if x != nil {
		return x.V
	}
	return ""
}

func (x *GetWeatherLifeByCityRes_LifeInfo_Chuanyi) GetDes() string {
	if x != nil {
		return x.Des
	}
	return ""
}

type GetWeatherLifeByCityRes_LifeInfo_Diaoyu struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	V   string `protobuf:"bytes,1,opt,name=v,proto3" json:"v,omitempty"`
	Des string `protobuf:"bytes,2,opt,name=des,proto3" json:"des,omitempty"`
}

func (x *GetWeatherLifeByCityRes_LifeInfo_Diaoyu) Reset() {
	*x = GetWeatherLifeByCityRes_LifeInfo_Diaoyu{}
	if protoimpl.UnsafeEnabled {
		mi := &file_growth_weather_weather_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetWeatherLifeByCityRes_LifeInfo_Diaoyu) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWeatherLifeByCityRes_LifeInfo_Diaoyu) ProtoMessage() {}

func (x *GetWeatherLifeByCityRes_LifeInfo_Diaoyu) ProtoReflect() protoreflect.Message {
	mi := &file_growth_weather_weather_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWeatherLifeByCityRes_LifeInfo_Diaoyu.ProtoReflect.Descriptor instead.
func (*GetWeatherLifeByCityRes_LifeInfo_Diaoyu) Descriptor() ([]byte, []int) {
	return file_growth_weather_weather_proto_rawDescGZIP(), []int{1, 0, 4}
}

func (x *GetWeatherLifeByCityRes_LifeInfo_Diaoyu) GetV() string {
	if x != nil {
		return x.V
	}
	return ""
}

func (x *GetWeatherLifeByCityRes_LifeInfo_Diaoyu) GetDes() string {
	if x != nil {
		return x.Des
	}
	return ""
}

type GetWeatherLifeByCityRes_LifeInfo_Ganmao struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	V   string `protobuf:"bytes,1,opt,name=v,proto3" json:"v,omitempty"`
	Des string `protobuf:"bytes,2,opt,name=des,proto3" json:"des,omitempty"`
}

func (x *GetWeatherLifeByCityRes_LifeInfo_Ganmao) Reset() {
	*x = GetWeatherLifeByCityRes_LifeInfo_Ganmao{}
	if protoimpl.UnsafeEnabled {
		mi := &file_growth_weather_weather_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetWeatherLifeByCityRes_LifeInfo_Ganmao) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWeatherLifeByCityRes_LifeInfo_Ganmao) ProtoMessage() {}

func (x *GetWeatherLifeByCityRes_LifeInfo_Ganmao) ProtoReflect() protoreflect.Message {
	mi := &file_growth_weather_weather_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWeatherLifeByCityRes_LifeInfo_Ganmao.ProtoReflect.Descriptor instead.
func (*GetWeatherLifeByCityRes_LifeInfo_Ganmao) Descriptor() ([]byte, []int) {
	return file_growth_weather_weather_proto_rawDescGZIP(), []int{1, 0, 5}
}

func (x *GetWeatherLifeByCityRes_LifeInfo_Ganmao) GetV() string {
	if x != nil {
		return x.V
	}
	return ""
}

func (x *GetWeatherLifeByCityRes_LifeInfo_Ganmao) GetDes() string {
	if x != nil {
		return x.Des
	}
	return ""
}

type GetWeatherLifeByCityRes_LifeInfo_Ziwaixian struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	V   string `protobuf:"bytes,1,opt,name=v,proto3" json:"v,omitempty"`
	Des string `protobuf:"bytes,2,opt,name=des,proto3" json:"des,omitempty"`
}

func (x *GetWeatherLifeByCityRes_LifeInfo_Ziwaixian) Reset() {
	*x = GetWeatherLifeByCityRes_LifeInfo_Ziwaixian{}
	if protoimpl.UnsafeEnabled {
		mi := &file_growth_weather_weather_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetWeatherLifeByCityRes_LifeInfo_Ziwaixian) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWeatherLifeByCityRes_LifeInfo_Ziwaixian) ProtoMessage() {}

func (x *GetWeatherLifeByCityRes_LifeInfo_Ziwaixian) ProtoReflect() protoreflect.Message {
	mi := &file_growth_weather_weather_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWeatherLifeByCityRes_LifeInfo_Ziwaixian.ProtoReflect.Descriptor instead.
func (*GetWeatherLifeByCityRes_LifeInfo_Ziwaixian) Descriptor() ([]byte, []int) {
	return file_growth_weather_weather_proto_rawDescGZIP(), []int{1, 0, 6}
}

func (x *GetWeatherLifeByCityRes_LifeInfo_Ziwaixian) GetV() string {
	if x != nil {
		return x.V
	}
	return ""
}

func (x *GetWeatherLifeByCityRes_LifeInfo_Ziwaixian) GetDes() string {
	if x != nil {
		return x.Des
	}
	return ""
}

type GetWeatherLifeByCityRes_LifeInfo_Xiche struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	V   string `protobuf:"bytes,1,opt,name=v,proto3" json:"v,omitempty"`
	Des string `protobuf:"bytes,2,opt,name=des,proto3" json:"des,omitempty"`
}

func (x *GetWeatherLifeByCityRes_LifeInfo_Xiche) Reset() {
	*x = GetWeatherLifeByCityRes_LifeInfo_Xiche{}
	if protoimpl.UnsafeEnabled {
		mi := &file_growth_weather_weather_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetWeatherLifeByCityRes_LifeInfo_Xiche) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWeatherLifeByCityRes_LifeInfo_Xiche) ProtoMessage() {}

func (x *GetWeatherLifeByCityRes_LifeInfo_Xiche) ProtoReflect() protoreflect.Message {
	mi := &file_growth_weather_weather_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWeatherLifeByCityRes_LifeInfo_Xiche.ProtoReflect.Descriptor instead.
func (*GetWeatherLifeByCityRes_LifeInfo_Xiche) Descriptor() ([]byte, []int) {
	return file_growth_weather_weather_proto_rawDescGZIP(), []int{1, 0, 7}
}

func (x *GetWeatherLifeByCityRes_LifeInfo_Xiche) GetV() string {
	if x != nil {
		return x.V
	}
	return ""
}

func (x *GetWeatherLifeByCityRes_LifeInfo_Xiche) GetDes() string {
	if x != nil {
		return x.Des
	}
	return ""
}

type GetWeatherLifeByCityRes_LifeInfo_Yundong struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	V   string `protobuf:"bytes,1,opt,name=v,proto3" json:"v,omitempty"`
	Des string `protobuf:"bytes,2,opt,name=des,proto3" json:"des,omitempty"`
}

func (x *GetWeatherLifeByCityRes_LifeInfo_Yundong) Reset() {
	*x = GetWeatherLifeByCityRes_LifeInfo_Yundong{}
	if protoimpl.UnsafeEnabled {
		mi := &file_growth_weather_weather_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetWeatherLifeByCityRes_LifeInfo_Yundong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWeatherLifeByCityRes_LifeInfo_Yundong) ProtoMessage() {}

func (x *GetWeatherLifeByCityRes_LifeInfo_Yundong) ProtoReflect() protoreflect.Message {
	mi := &file_growth_weather_weather_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWeatherLifeByCityRes_LifeInfo_Yundong.ProtoReflect.Descriptor instead.
func (*GetWeatherLifeByCityRes_LifeInfo_Yundong) Descriptor() ([]byte, []int) {
	return file_growth_weather_weather_proto_rawDescGZIP(), []int{1, 0, 8}
}

func (x *GetWeatherLifeByCityRes_LifeInfo_Yundong) GetV() string {
	if x != nil {
		return x.V
	}
	return ""
}

func (x *GetWeatherLifeByCityRes_LifeInfo_Yundong) GetDes() string {
	if x != nil {
		return x.Des
	}
	return ""
}

type GetWeatherLifeByCityRes_LifeInfo_Daisan struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	V   string `protobuf:"bytes,1,opt,name=v,proto3" json:"v,omitempty"`
	Des string `protobuf:"bytes,2,opt,name=des,proto3" json:"des,omitempty"`
}

func (x *GetWeatherLifeByCityRes_LifeInfo_Daisan) Reset() {
	*x = GetWeatherLifeByCityRes_LifeInfo_Daisan{}
	if protoimpl.UnsafeEnabled {
		mi := &file_growth_weather_weather_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetWeatherLifeByCityRes_LifeInfo_Daisan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWeatherLifeByCityRes_LifeInfo_Daisan) ProtoMessage() {}

func (x *GetWeatherLifeByCityRes_LifeInfo_Daisan) ProtoReflect() protoreflect.Message {
	mi := &file_growth_weather_weather_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWeatherLifeByCityRes_LifeInfo_Daisan.ProtoReflect.Descriptor instead.
func (*GetWeatherLifeByCityRes_LifeInfo_Daisan) Descriptor() ([]byte, []int) {
	return file_growth_weather_weather_proto_rawDescGZIP(), []int{1, 0, 9}
}

func (x *GetWeatherLifeByCityRes_LifeInfo_Daisan) GetV() string {
	if x != nil {
		return x.V
	}
	return ""
}

func (x *GetWeatherLifeByCityRes_LifeInfo_Daisan) GetDes() string {
	if x != nil {
		return x.Des
	}
	return ""
}

type WeatherInfo_Realtime struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Temperature string `protobuf:"bytes,1,opt,name=temperature,proto3" json:"temperature,omitempty"`
	Humidity    string `protobuf:"bytes,2,opt,name=humidity,proto3" json:"humidity,omitempty"`
	Info        string `protobuf:"bytes,3,opt,name=info,proto3" json:"info,omitempty"`
	Wid         string `protobuf:"bytes,4,opt,name=wid,proto3" json:"wid,omitempty"`
	Direct      string `protobuf:"bytes,5,opt,name=direct,proto3" json:"direct,omitempty"`
	Power       string `protobuf:"bytes,6,opt,name=power,proto3" json:"power,omitempty"`
	Aqi         string `protobuf:"bytes,7,opt,name=aqi,proto3" json:"aqi,omitempty"`
}

func (x *WeatherInfo_Realtime) Reset() {
	*x = WeatherInfo_Realtime{}
	if protoimpl.UnsafeEnabled {
		mi := &file_growth_weather_weather_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WeatherInfo_Realtime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeatherInfo_Realtime) ProtoMessage() {}

func (x *WeatherInfo_Realtime) ProtoReflect() protoreflect.Message {
	mi := &file_growth_weather_weather_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeatherInfo_Realtime.ProtoReflect.Descriptor instead.
func (*WeatherInfo_Realtime) Descriptor() ([]byte, []int) {
	return file_growth_weather_weather_proto_rawDescGZIP(), []int{4, 0}
}

func (x *WeatherInfo_Realtime) GetTemperature() string {
	if x != nil {
		return x.Temperature
	}
	return ""
}

func (x *WeatherInfo_Realtime) GetHumidity() string {
	if x != nil {
		return x.Humidity
	}
	return ""
}

func (x *WeatherInfo_Realtime) GetInfo() string {
	if x != nil {
		return x.Info
	}
	return ""
}

func (x *WeatherInfo_Realtime) GetWid() string {
	if x != nil {
		return x.Wid
	}
	return ""
}

func (x *WeatherInfo_Realtime) GetDirect() string {
	if x != nil {
		return x.Direct
	}
	return ""
}

func (x *WeatherInfo_Realtime) GetPower() string {
	if x != nil {
		return x.Power
	}
	return ""
}

func (x *WeatherInfo_Realtime) GetAqi() string {
	if x != nil {
		return x.Aqi
	}
	return ""
}

type WeatherInfo_Future struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Date        string `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	Temperature string `protobuf:"bytes,2,opt,name=temperature,proto3" json:"temperature,omitempty"`
	Weather     string `protobuf:"bytes,3,opt,name=weather,proto3" json:"weather,omitempty"`
	Direct      string `protobuf:"bytes,4,opt,name=direct,proto3" json:"direct,omitempty"`
	WidDay      string `protobuf:"bytes,5,opt,name=wid_day,json=widDay,proto3" json:"wid_day,omitempty"`
	WidNight    string `protobuf:"bytes,6,opt,name=wid_night,json=widNight,proto3" json:"wid_night,omitempty"`
}

func (x *WeatherInfo_Future) Reset() {
	*x = WeatherInfo_Future{}
	if protoimpl.UnsafeEnabled {
		mi := &file_growth_weather_weather_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WeatherInfo_Future) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeatherInfo_Future) ProtoMessage() {}

func (x *WeatherInfo_Future) ProtoReflect() protoreflect.Message {
	mi := &file_growth_weather_weather_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeatherInfo_Future.ProtoReflect.Descriptor instead.
func (*WeatherInfo_Future) Descriptor() ([]byte, []int) {
	return file_growth_weather_weather_proto_rawDescGZIP(), []int{4, 1}
}

func (x *WeatherInfo_Future) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *WeatherInfo_Future) GetTemperature() string {
	if x != nil {
		return x.Temperature
	}
	return ""
}

func (x *WeatherInfo_Future) GetWeather() string {
	if x != nil {
		return x.Weather
	}
	return ""
}

func (x *WeatherInfo_Future) GetDirect() string {
	if x != nil {
		return x.Direct
	}
	return ""
}

func (x *WeatherInfo_Future) GetWidDay() string {
	if x != nil {
		return x.WidDay
	}
	return ""
}

func (x *WeatherInfo_Future) GetWidNight() string {
	if x != nil {
		return x.WidNight
	}
	return ""
}

var File_growth_weather_weather_proto protoreflect.FileDescriptor

var file_growth_weather_weather_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x67, 0x72, 0x6f, 0x77, 0x74, 0x68, 0x2f, 0x77, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72,
	0x2f, 0x77, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70,
	0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x2d, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x57, 0x65, 0x61, 0x74, 0x68, 0x65,
	0x72, 0x4c, 0x69, 0x66, 0x65, 0x42, 0x79, 0x43, 0x69, 0x74, 0x79, 0x52, 0x65, 0x71, 0x12, 0x12,
	0x0a, 0x04, 0x63, 0x69, 0x74, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x69,
	0x74, 0x79, 0x22, 0x9d, 0x0a, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x57, 0x65, 0x61, 0x74, 0x68, 0x65,
	0x72, 0x4c, 0x69, 0x66, 0x65, 0x42, 0x79, 0x43, 0x69, 0x74, 0x79, 0x52, 0x65, 0x73, 0x12, 0x12,
	0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6d, 0x73, 0x67, 0x12, 0x3b, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x27, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x57, 0x65,
	0x61, 0x74, 0x68, 0x65, 0x72, 0x4c, 0x69, 0x66, 0x65, 0x42, 0x79, 0x43, 0x69, 0x74, 0x79, 0x52,
	0x65, 0x73, 0x2e, 0x4c, 0x69, 0x66, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x1a, 0x9e, 0x09, 0x0a, 0x08, 0x4c, 0x69, 0x66, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x4c,
	0x0a, 0x08, 0x6b, 0x6f, 0x6e, 0x67, 0x74, 0x69, 0x61, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x30, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x57, 0x65, 0x61, 0x74,
	0x68, 0x65, 0x72, 0x4c, 0x69, 0x66, 0x65, 0x42, 0x79, 0x43, 0x69, 0x74, 0x79, 0x52, 0x65, 0x73,
	0x2e, 0x4c, 0x69, 0x66, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x4b, 0x6f, 0x6e, 0x67, 0x74, 0x69,
	0x61, 0x6f, 0x52, 0x08, 0x6b, 0x6f, 0x6e, 0x67, 0x74, 0x69, 0x61, 0x6f, 0x12, 0x46, 0x0a, 0x06,
	0x67, 0x75, 0x6f, 0x6d, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x57, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x4c,
	0x69, 0x66, 0x65, 0x42, 0x79, 0x43, 0x69, 0x74, 0x79, 0x52, 0x65, 0x73, 0x2e, 0x4c, 0x69, 0x66,
	0x65, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x47, 0x75, 0x6f, 0x6d, 0x69, 0x6e, 0x52, 0x06, 0x67, 0x75,
	0x6f, 0x6d, 0x69, 0x6e, 0x12, 0x4c, 0x0a, 0x08, 0x73, 0x68, 0x75, 0x73, 0x68, 0x69, 0x64, 0x75,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x30, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47,
	0x65, 0x74, 0x57, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x4c, 0x69, 0x66, 0x65, 0x42, 0x79, 0x43,
	0x69, 0x74, 0x79, 0x52, 0x65, 0x73, 0x2e, 0x4c, 0x69, 0x66, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x2e,
	0x53, 0x68, 0x75, 0x73, 0x68, 0x69, 0x64, 0x75, 0x52, 0x08, 0x73, 0x68, 0x75, 0x73, 0x68, 0x69,
	0x64, 0x75, 0x12, 0x49, 0x0a, 0x07, 0x63, 0x68, 0x75, 0x61, 0x6e, 0x79, 0x69, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x2f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x57,
	0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x4c, 0x69, 0x66, 0x65, 0x42, 0x79, 0x43, 0x69, 0x74, 0x79,
	0x52, 0x65, 0x73, 0x2e, 0x4c, 0x69, 0x66, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x43, 0x68, 0x75,
	0x61, 0x6e, 0x79, 0x69, 0x52, 0x07, 0x63, 0x68, 0x75, 0x61, 0x6e, 0x79, 0x69, 0x12, 0x46, 0x0a,
	0x06, 0x64, 0x69, 0x61, 0x6f, 0x79, 0x75, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x57, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72,
	0x4c, 0x69, 0x66, 0x65, 0x42, 0x79, 0x43, 0x69, 0x74, 0x79, 0x52, 0x65, 0x73, 0x2e, 0x4c, 0x69,
	0x66, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x44, 0x69, 0x61, 0x6f, 0x79, 0x75, 0x52, 0x06, 0x64,
	0x69, 0x61, 0x6f, 0x79, 0x75, 0x12, 0x46, 0x0a, 0x06, 0x67, 0x61, 0x6e, 0x6d, 0x61, 0x6f, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65,
	0x74, 0x57, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x4c, 0x69, 0x66, 0x65, 0x42, 0x79, 0x43, 0x69,
	0x74, 0x79, 0x52, 0x65, 0x73, 0x2e, 0x4c, 0x69, 0x66, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x47,
	0x61, 0x6e, 0x6d, 0x61, 0x6f, 0x52, 0x06, 0x67, 0x61, 0x6e, 0x6d, 0x61, 0x6f, 0x12, 0x4f, 0x0a,
	0x09, 0x7a, 0x69, 0x77, 0x61, 0x69, 0x78, 0x69, 0x61, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x57, 0x65, 0x61, 0x74,
	0x68, 0x65, 0x72, 0x4c, 0x69, 0x66, 0x65, 0x42, 0x79, 0x43, 0x69, 0x74, 0x79, 0x52, 0x65, 0x73,
	0x2e, 0x4c, 0x69, 0x66, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x5a, 0x69, 0x77, 0x61, 0x69, 0x78,
	0x69, 0x61, 0x6e, 0x52, 0x09, 0x7a, 0x69, 0x77, 0x61, 0x69, 0x78, 0x69, 0x61, 0x6e, 0x12, 0x43,
	0x0a, 0x05, 0x78, 0x69, 0x63, 0x68, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2d, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x57, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72,
	0x4c, 0x69, 0x66, 0x65, 0x42, 0x79, 0x43, 0x69, 0x74, 0x79, 0x52, 0x65, 0x73, 0x2e, 0x4c, 0x69,
	0x66, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x58, 0x69, 0x63, 0x68, 0x65, 0x52, 0x05, 0x78, 0x69,
	0x63, 0x68, 0x65, 0x12, 0x49, 0x0a, 0x07, 0x79, 0x75, 0x6e, 0x64, 0x6f, 0x6e, 0x67, 0x18, 0x09,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x2f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74,
	0x57, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x4c, 0x69, 0x66, 0x65, 0x42, 0x79, 0x43, 0x69, 0x74,
	0x79, 0x52, 0x65, 0x73, 0x2e, 0x4c, 0x69, 0x66, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x59, 0x75,
	0x6e, 0x64, 0x6f, 0x6e, 0x67, 0x52, 0x07, 0x79, 0x75, 0x6e, 0x64, 0x6f, 0x6e, 0x67, 0x12, 0x46,
	0x0a, 0x06, 0x64, 0x61, 0x69, 0x73, 0x61, 0x6e, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2e,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x57, 0x65, 0x61, 0x74, 0x68, 0x65,
	0x72, 0x4c, 0x69, 0x66, 0x65, 0x42, 0x79, 0x43, 0x69, 0x74, 0x79, 0x52, 0x65, 0x73, 0x2e, 0x4c,
	0x69, 0x66, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x44, 0x61, 0x69, 0x73, 0x61, 0x6e, 0x52, 0x06,
	0x64, 0x61, 0x69, 0x73, 0x61, 0x6e, 0x1a, 0x2a, 0x0a, 0x08, 0x4b, 0x6f, 0x6e, 0x67, 0x74, 0x69,
	0x61, 0x6f, 0x12, 0x0c, 0x0a, 0x01, 0x76, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x01, 0x76,
	0x12, 0x10, 0x0a, 0x03, 0x64, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x64,
	0x65, 0x73, 0x1a, 0x28, 0x0a, 0x06, 0x47, 0x75, 0x6f, 0x6d, 0x69, 0x6e, 0x12, 0x0c, 0x0a, 0x01,
	0x76, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x01, 0x76, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x65,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x64, 0x65, 0x73, 0x1a, 0x2a, 0x0a, 0x08,
	0x53, 0x68, 0x75, 0x73, 0x68, 0x69, 0x64, 0x75, 0x12, 0x0c, 0x0a, 0x01, 0x76, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x01, 0x76, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x65, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x64, 0x65, 0x73, 0x1a, 0x29, 0x0a, 0x07, 0x43, 0x68, 0x75, 0x61,
	0x6e, 0x79, 0x69, 0x12, 0x0c, 0x0a, 0x01, 0x76, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x01,
	0x76, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x64, 0x65, 0x73, 0x1a, 0x28, 0x0a, 0x06, 0x44, 0x69, 0x61, 0x6f, 0x79, 0x75, 0x12, 0x0c, 0x0a,
	0x01, 0x76, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x01, 0x76, 0x12, 0x10, 0x0a, 0x03, 0x64,
	0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x64, 0x65, 0x73, 0x1a, 0x28, 0x0a,
	0x06, 0x47, 0x61, 0x6e, 0x6d, 0x61, 0x6f, 0x12, 0x0c, 0x0a, 0x01, 0x76, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x01, 0x76, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x64, 0x65, 0x73, 0x1a, 0x2b, 0x0a, 0x09, 0x5a, 0x69, 0x77, 0x61, 0x69,
	0x78, 0x69, 0x61, 0x6e, 0x12, 0x0c, 0x0a, 0x01, 0x76, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x01, 0x76, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x64, 0x65, 0x73, 0x1a, 0x27, 0x0a, 0x05, 0x58, 0x69, 0x63, 0x68, 0x65, 0x12, 0x0c, 0x0a,
	0x01, 0x76, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x01, 0x76, 0x12, 0x10, 0x0a, 0x03, 0x64,
	0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x64, 0x65, 0x73, 0x1a, 0x29, 0x0a,
	0x07, 0x59, 0x75, 0x6e, 0x64, 0x6f, 0x6e, 0x67, 0x12, 0x0c, 0x0a, 0x01, 0x76, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x01, 0x76, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x65, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x64, 0x65, 0x73, 0x1a, 0x28, 0x0a, 0x06, 0x44, 0x61, 0x69, 0x73,
	0x61, 0x6e, 0x12, 0x0c, 0x0a, 0x01, 0x76, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x01, 0x76,
	0x12, 0x10, 0x0a, 0x03, 0x64, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x64,
	0x65, 0x73, 0x22, 0x29, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x57, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72,
	0x42, 0x79, 0x43, 0x69, 0x74, 0x79, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x69, 0x74,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x69, 0x74, 0x79, 0x22, 0x63, 0x0a,
	0x13, 0x47, 0x65, 0x74, 0x57, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x42, 0x79, 0x43, 0x69, 0x74,
	0x79, 0x52, 0x65, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x26, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x57, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x22, 0xd3, 0x03, 0x0a, 0x0b, 0x57, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x37, 0x0a, 0x08, 0x72, 0x65, 0x61, 0x6c, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x57, 0x65, 0x61,
	0x74, 0x68, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x52, 0x65, 0x61, 0x6c, 0x74, 0x69, 0x6d,
	0x65, 0x52, 0x08, 0x72, 0x65, 0x61, 0x6c, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x31, 0x0a, 0x06, 0x66,
	0x75, 0x74, 0x75, 0x72, 0x65, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x57, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x2e,
	0x46, 0x75, 0x74, 0x75, 0x72, 0x65, 0x52, 0x06, 0x66, 0x75, 0x74, 0x75, 0x72, 0x65, 0x1a, 0xae,
	0x01, 0x0a, 0x08, 0x52, 0x65, 0x61, 0x6c, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x74,
	0x65, 0x6d, 0x70, 0x65, 0x72, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x74, 0x65, 0x6d, 0x70, 0x65, 0x72, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x68, 0x75, 0x6d, 0x69, 0x64, 0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x68, 0x75, 0x6d, 0x69, 0x64, 0x69, 0x74, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x6e, 0x66,
	0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x12, 0x10, 0x0a,
	0x03, 0x77, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x77, 0x69, 0x64, 0x12,
	0x16, 0x0a, 0x06, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x6f, 0x77, 0x65, 0x72,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x6f, 0x77, 0x65, 0x72, 0x12, 0x10, 0x0a,
	0x03, 0x61, 0x71, 0x69, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x61, 0x71, 0x69, 0x1a,
	0xa6, 0x01, 0x0a, 0x06, 0x46, 0x75, 0x74, 0x75, 0x72, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x65, 0x12, 0x20,
	0x0a, 0x0b, 0x74, 0x65, 0x6d, 0x70, 0x65, 0x72, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x74, 0x65, 0x6d, 0x70, 0x65, 0x72, 0x61, 0x74, 0x75, 0x72, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x77, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x77, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x69,
	0x72, 0x65, 0x63, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x69, 0x72, 0x65,
	0x63, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x77, 0x69, 0x64, 0x5f, 0x64, 0x61, 0x79, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x77, 0x69, 0x64, 0x44, 0x61, 0x79, 0x12, 0x1b, 0x0a, 0x09, 0x77,
	0x69, 0x64, 0x5f, 0x6e, 0x69, 0x67, 0x68, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x77, 0x69, 0x64, 0x4e, 0x69, 0x67, 0x68, 0x74, 0x32, 0xff, 0x01, 0x0a, 0x07, 0x57, 0x65, 0x61,
	0x74, 0x68, 0x65, 0x72, 0x12, 0x73, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x57, 0x65, 0x61, 0x74, 0x68,
	0x65, 0x72, 0x42, 0x79, 0x43, 0x69, 0x74, 0x79, 0x12, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x47, 0x65, 0x74, 0x57, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x42, 0x79, 0x43, 0x69, 0x74,
	0x79, 0x52, 0x65, 0x71, 0x1a, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74,
	0x57, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x42, 0x79, 0x43, 0x69, 0x74, 0x79, 0x52, 0x65, 0x73,
	0x22, 0x27, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x21, 0x22, 0x1c, 0x2f, 0x76, 0x31, 0x2f, 0x77, 0x65,
	0x61, 0x74, 0x68, 0x65, 0x72, 0x2f, 0x67, 0x65, 0x74, 0x57, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72,
	0x42, 0x79, 0x44, 0x61, 0x74, 0x65, 0x3a, 0x01, 0x2a, 0x12, 0x7f, 0x0a, 0x14, 0x47, 0x65, 0x74,
	0x57, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x4c, 0x69, 0x66, 0x65, 0x42, 0x79, 0x43, 0x69, 0x74,
	0x79, 0x12, 0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x57, 0x65, 0x61,
	0x74, 0x68, 0x65, 0x72, 0x4c, 0x69, 0x66, 0x65, 0x42, 0x79, 0x43, 0x69, 0x74, 0x79, 0x52, 0x65,
	0x71, 0x1a, 0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x57, 0x65, 0x61,
	0x74, 0x68, 0x65, 0x72, 0x4c, 0x69, 0x66, 0x65, 0x42, 0x79, 0x43, 0x69, 0x74, 0x79, 0x52, 0x65,
	0x73, 0x22, 0x27, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x21, 0x22, 0x1c, 0x2f, 0x76, 0x31, 0x2f, 0x77,
	0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x2f, 0x67, 0x65, 0x74, 0x57, 0x65, 0x61, 0x74, 0x68, 0x65,
	0x72, 0x42, 0x79, 0x44, 0x61, 0x74, 0x65, 0x3a, 0x01, 0x2a, 0x42, 0x0f, 0x5a, 0x0d, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x2f, 0x77, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_growth_weather_weather_proto_rawDescOnce sync.Once
	file_growth_weather_weather_proto_rawDescData = file_growth_weather_weather_proto_rawDesc
)

func file_growth_weather_weather_proto_rawDescGZIP() []byte {
	file_growth_weather_weather_proto_rawDescOnce.Do(func() {
		file_growth_weather_weather_proto_rawDescData = protoimpl.X.CompressGZIP(file_growth_weather_weather_proto_rawDescData)
	})
	return file_growth_weather_weather_proto_rawDescData
}

var file_growth_weather_weather_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_growth_weather_weather_proto_goTypes = []interface{}{
	(*GetWeatherLifeByCityReq)(nil),                    // 0: proto.GetWeatherLifeByCityReq
	(*GetWeatherLifeByCityRes)(nil),                    // 1: proto.GetWeatherLifeByCityRes
	(*GetWeatherByCityReq)(nil),                        // 2: proto.GetWeatherByCityReq
	(*GetWeatherByCityRes)(nil),                        // 3: proto.GetWeatherByCityRes
	(*WeatherInfo)(nil),                                // 4: proto.WeatherInfo
	(*GetWeatherLifeByCityRes_LifeInfo)(nil),           // 5: proto.GetWeatherLifeByCityRes.LifeInfo
	(*GetWeatherLifeByCityRes_LifeInfo_Kongtiao)(nil),  // 6: proto.GetWeatherLifeByCityRes.LifeInfo.Kongtiao
	(*GetWeatherLifeByCityRes_LifeInfo_Guomin)(nil),    // 7: proto.GetWeatherLifeByCityRes.LifeInfo.Guomin
	(*GetWeatherLifeByCityRes_LifeInfo_Shushidu)(nil),  // 8: proto.GetWeatherLifeByCityRes.LifeInfo.Shushidu
	(*GetWeatherLifeByCityRes_LifeInfo_Chuanyi)(nil),   // 9: proto.GetWeatherLifeByCityRes.LifeInfo.Chuanyi
	(*GetWeatherLifeByCityRes_LifeInfo_Diaoyu)(nil),    // 10: proto.GetWeatherLifeByCityRes.LifeInfo.Diaoyu
	(*GetWeatherLifeByCityRes_LifeInfo_Ganmao)(nil),    // 11: proto.GetWeatherLifeByCityRes.LifeInfo.Ganmao
	(*GetWeatherLifeByCityRes_LifeInfo_Ziwaixian)(nil), // 12: proto.GetWeatherLifeByCityRes.LifeInfo.Ziwaixian
	(*GetWeatherLifeByCityRes_LifeInfo_Xiche)(nil),     // 13: proto.GetWeatherLifeByCityRes.LifeInfo.Xiche
	(*GetWeatherLifeByCityRes_LifeInfo_Yundong)(nil),   // 14: proto.GetWeatherLifeByCityRes.LifeInfo.Yundong
	(*GetWeatherLifeByCityRes_LifeInfo_Daisan)(nil),    // 15: proto.GetWeatherLifeByCityRes.LifeInfo.Daisan
	(*WeatherInfo_Realtime)(nil),                       // 16: proto.WeatherInfo.Realtime
	(*WeatherInfo_Future)(nil),                         // 17: proto.WeatherInfo.Future
}
var file_growth_weather_weather_proto_depIdxs = []int32{
	5,  // 0: proto.GetWeatherLifeByCityRes.data:type_name -> proto.GetWeatherLifeByCityRes.LifeInfo
	4,  // 1: proto.GetWeatherByCityRes.data:type_name -> proto.WeatherInfo
	16, // 2: proto.WeatherInfo.realtime:type_name -> proto.WeatherInfo.Realtime
	17, // 3: proto.WeatherInfo.future:type_name -> proto.WeatherInfo.Future
	6,  // 4: proto.GetWeatherLifeByCityRes.LifeInfo.kongtiao:type_name -> proto.GetWeatherLifeByCityRes.LifeInfo.Kongtiao
	7,  // 5: proto.GetWeatherLifeByCityRes.LifeInfo.guomin:type_name -> proto.GetWeatherLifeByCityRes.LifeInfo.Guomin
	8,  // 6: proto.GetWeatherLifeByCityRes.LifeInfo.shushidu:type_name -> proto.GetWeatherLifeByCityRes.LifeInfo.Shushidu
	9,  // 7: proto.GetWeatherLifeByCityRes.LifeInfo.chuanyi:type_name -> proto.GetWeatherLifeByCityRes.LifeInfo.Chuanyi
	10, // 8: proto.GetWeatherLifeByCityRes.LifeInfo.diaoyu:type_name -> proto.GetWeatherLifeByCityRes.LifeInfo.Diaoyu
	11, // 9: proto.GetWeatherLifeByCityRes.LifeInfo.ganmao:type_name -> proto.GetWeatherLifeByCityRes.LifeInfo.Ganmao
	12, // 10: proto.GetWeatherLifeByCityRes.LifeInfo.ziwaixian:type_name -> proto.GetWeatherLifeByCityRes.LifeInfo.Ziwaixian
	13, // 11: proto.GetWeatherLifeByCityRes.LifeInfo.xiche:type_name -> proto.GetWeatherLifeByCityRes.LifeInfo.Xiche
	14, // 12: proto.GetWeatherLifeByCityRes.LifeInfo.yundong:type_name -> proto.GetWeatherLifeByCityRes.LifeInfo.Yundong
	15, // 13: proto.GetWeatherLifeByCityRes.LifeInfo.daisan:type_name -> proto.GetWeatherLifeByCityRes.LifeInfo.Daisan
	2,  // 14: proto.Weather.GetWeatherByCity:input_type -> proto.GetWeatherByCityReq
	0,  // 15: proto.Weather.GetWeatherLifeByCity:input_type -> proto.GetWeatherLifeByCityReq
	3,  // 16: proto.Weather.GetWeatherByCity:output_type -> proto.GetWeatherByCityRes
	1,  // 17: proto.Weather.GetWeatherLifeByCity:output_type -> proto.GetWeatherLifeByCityRes
	16, // [16:18] is the sub-list for method output_type
	14, // [14:16] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_growth_weather_weather_proto_init() }
func file_growth_weather_weather_proto_init() {
	if File_growth_weather_weather_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_growth_weather_weather_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetWeatherLifeByCityReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_growth_weather_weather_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetWeatherLifeByCityRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_growth_weather_weather_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetWeatherByCityReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_growth_weather_weather_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetWeatherByCityRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_growth_weather_weather_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WeatherInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_growth_weather_weather_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetWeatherLifeByCityRes_LifeInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_growth_weather_weather_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetWeatherLifeByCityRes_LifeInfo_Kongtiao); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_growth_weather_weather_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetWeatherLifeByCityRes_LifeInfo_Guomin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_growth_weather_weather_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetWeatherLifeByCityRes_LifeInfo_Shushidu); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_growth_weather_weather_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetWeatherLifeByCityRes_LifeInfo_Chuanyi); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_growth_weather_weather_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetWeatherLifeByCityRes_LifeInfo_Diaoyu); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_growth_weather_weather_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetWeatherLifeByCityRes_LifeInfo_Ganmao); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_growth_weather_weather_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetWeatherLifeByCityRes_LifeInfo_Ziwaixian); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_growth_weather_weather_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetWeatherLifeByCityRes_LifeInfo_Xiche); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_growth_weather_weather_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetWeatherLifeByCityRes_LifeInfo_Yundong); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_growth_weather_weather_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetWeatherLifeByCityRes_LifeInfo_Daisan); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_growth_weather_weather_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WeatherInfo_Realtime); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_growth_weather_weather_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WeatherInfo_Future); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_growth_weather_weather_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_growth_weather_weather_proto_goTypes,
		DependencyIndexes: file_growth_weather_weather_proto_depIdxs,
		MessageInfos:      file_growth_weather_weather_proto_msgTypes,
	}.Build()
	File_growth_weather_weather_proto = out.File
	file_growth_weather_weather_proto_rawDesc = nil
	file_growth_weather_weather_proto_goTypes = nil
	file_growth_weather_weather_proto_depIdxs = nil
}
