// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package wx_notify

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// WxNotifyServiceClient is the client API for WxNotifyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WxNotifyServiceClient interface {
	SendCustomMsg(ctx context.Context, in *WxCustmoMsgRequest, opts ...grpc.CallOption) (*WxCustmoMsgResponse, error)
}

type wxNotifyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWxNotifyServiceClient(cc grpc.ClientConnInterface) WxNotifyServiceClient {
	return &wxNotifyServiceClient{cc}
}

func (c *wxNotifyServiceClient) SendCustomMsg(ctx context.Context, in *WxCustmoMsgRequest, opts ...grpc.CallOption) (*WxCustmoMsgResponse, error) {
	out := new(WxCustmoMsgResponse)
	err := c.cc.Invoke(ctx, "/proto.WxNotifyService/SendCustomMsg", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WxNotifyServiceServer is the server API for WxNotifyService service.
// All implementations must embed UnimplementedWxNotifyServiceServer
// for forward compatibility
type WxNotifyServiceServer interface {
	SendCustomMsg(context.Context, *WxCustmoMsgRequest) (*WxCustmoMsgResponse, error)
	mustEmbedUnimplementedWxNotifyServiceServer()
}

// UnimplementedWxNotifyServiceServer must be embedded to have forward compatible implementations.
type UnimplementedWxNotifyServiceServer struct {
}

func (UnimplementedWxNotifyServiceServer) SendCustomMsg(context.Context, *WxCustmoMsgRequest) (*WxCustmoMsgResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendCustomMsg not implemented")
}
func (UnimplementedWxNotifyServiceServer) mustEmbedUnimplementedWxNotifyServiceServer() {}

// UnsafeWxNotifyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WxNotifyServiceServer will
// result in compilation errors.
type UnsafeWxNotifyServiceServer interface {
	mustEmbedUnimplementedWxNotifyServiceServer()
}

func RegisterWxNotifyServiceServer(s grpc.ServiceRegistrar, srv WxNotifyServiceServer) {
	s.RegisterService(&WxNotifyService_ServiceDesc, srv)
}

func _WxNotifyService_SendCustomMsg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WxCustmoMsgRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WxNotifyServiceServer).SendCustomMsg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.WxNotifyService/SendCustomMsg",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WxNotifyServiceServer).SendCustomMsg(ctx, req.(*WxCustmoMsgRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WxNotifyService_ServiceDesc is the grpc.ServiceDesc for WxNotifyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WxNotifyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.WxNotifyService",
	HandlerType: (*WxNotifyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendCustomMsg",
			Handler:    _WxNotifyService_SendCustomMsg_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "growth/wx_notify/wx_notify.proto",
}
